name: Build & Push to ECR

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      #소스코드 가져오기
      - name: Checkout
        uses: actions/checkout@v3

      # AWS 자격 정보 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ECR 로그인()
      # 도커 이미지 빌드, 이미지 태크 변경(ECR설정에 맞게), 이미지 ECR로 푸시
